### ISSUE TITLE
[Todo] 배울 예정 기술

### ISSUE THREAD

**Issue by Bhanjo** [Bhanjo/next-playground#4]
- [ ] next.js 페이지 렌더링 방식 복습하기
- [ ] 정적, 동적 라우팅 방식 공부
- [ ] SWR을 통한 데이터 패치 공부
